config/routes.rb
SocialStudy::Application.routes.draw do

  resources :entries, except: [:show, :create] do
    collection do
      get 'next/:title', action: 'next'
      get 'history'
    end
  end

  match "/search" => "search#index", :as => :search

  resources :reviews, except: [:index]
  resources :notes, except: [:index]
  resources :experiences, except: [:index]
  resources :reminds, only: [:index] do
    collection do
      get :short_index
    end
  end

  resources :comments, only: [:create, :destroy] do
    collection do
      get :paginate
    end
  end


  resources :microblogs
  resources :states, only: [:show, :destroy] do
    member do
      post :relay
    end
  end


  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  resources :users, :only => [:show, :update] do
    member do
      post :follow
      post :unfollow
      get :following
      get :followers
      post :vote
      post :study
      post :grade
      post :collect
      get :states
      get :describe
      get :cancel_describe
      put :update_describe
      get :knowledges
      get :resources
      get :reviews
      get :notes
      get :experiences
    end
  end
  resources :knowledges, expect: :destroy do
    member do
      get :notes
      get :experiences
      get :my
    end
    collection do
      get :top
      get :top_experiences
      get :top_notes
    end
  end

  resources :resources, expect: :destroy do
    collection do
      get :top
      get :top_experiences
      get :top_reviews
    end
  end

  root :to => "states#index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Post

  has_many :reputations, as: :reputable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  belongs_to :knowledge

  attr_accessible :user_id, :knowledge_id, :title, :content, :knowledge

  validates_presence_of :user_id, :knowledge_id, :title, :content

  alias_method :itemable, :knowledge

  index :user_id => 1
  index :knowledge_id => 1

  field :title, type: String
  field :content, type: String
  field :reputations_count, type: Integer, default: 0

  scope :top, ->(num=nil){ desc(:reputations_count).limit(num) }

  def repute_count(type)
    self.reputations.where(type: type).count
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  load_and_authorize_resource
  before_filter :require_user, except: [:show, :index]
  layout :choose_post_layout

  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @note = Note.find(params[:id])
    @knowledge = @note.knowledge
  end

  def new
    @note = current_user.notes.build(knowledge_id: params[:knowledge_id])
    @knowledge = Knowledge.find(params[:knowledge_id])
  end

  def edit
    @note = Note.find(params[:id])
    @knowledge = @note.knowledge
  end

  def create
    @note = current_user.notes.build(params[:note])
    @knowledge = @note.knowledge

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @note = Note.find(params[:id])
    @knowledge = @note.knowledge

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to @note.knowledge }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_for @note do |f|
  .field
    = f.label :content, '标题'
    = f.text_field :title

  .field
    = f.label :content, '内容'
    = f.text_area :content, class: 'textarea'

    = f.hidden_field :knowledge_id, valuse: params[:knowledge_id]

  .form-actions
    = f.submit '提交', class: 'btn btn-success'
    &nbsp;
    = link_to '返回', (@note.new_record? ? @knowledge : @note), class: 'btn'

app/views/notes/_top.haml
- if @notes.present?
  %h3
    %small 热门笔记
  %br
  - @notes.each do |note|
    %div.span5{style: 'padding-bottom: 15px;'}
      %div
        =link_to note.user do
          = image_tag note.user.image(:small), class: 'user-face'
      %div.pull-left
        %span
          =link_to note do
            %strong #{note.title}
          %br.big
          =link_to note.user.name, note.user
          的
          =link_to note.knowledge.title, note.knowledge
          笔记
          %br.big
        %small
          ="#{note.reputations.useful.count}有用 #{note.created_at.getlocal.to_date}"

app/views/notes/edit.html.haml
%h3
  = "修改 #{@knowledge.title} 的笔记"
%hr

= render 'form'

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @notes.each do |note|
    %tr
      %td= note.title
      %td= note.content
      %td= link_to 'Show', note
      %td= link_to 'Edit', edit_note_path(note)
      %td= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h3
  = "写 #{@knowledge.title} 的笔记"
%hr

= render 'form'

app/views/notes/show.html.haml
%div.post
  %h4.pull-left
    = "#{@note.knowledge.title} 的笔记 - #{@note.title}"

  %div.pull-right
    %div.reputations
      -if operable(@note)
        = link_to edit_note_path(@note) do
          %i.icon-edit
        %span.w5
        = link_to @note, method: :delete, confirm: '你确定要删除这条笔记吗？'  do
          %i.icon-trash

  %br
  %br
  = link_to @note.user.name, @note.user
  在学
  = link_to @knowledge.title, @knowledge

  -if operable(@note)
    = link_to new_note_path(knowledge_id: @knowledge.id), class: 'pull-right' do
      继续写笔记
  %hr.clear

%div.text
  = raw @note.content

%br.big

-if current_user
  .pull-right
    = collect_link(@note)
    &nbsp;
    =link_to vote_path(@note, 'useful'), remote: true, method: :post do
      %i.icon-thumbs-up
    %span.useful-count
      =@note.repute_count('useful')

    &nbsp;
    =link_to vote_path(@note, 'useless'), remote: true, method: :post do
      %i.icon-thumbs-down
    %span.useless-count
      =@note.repute_count('useless')
  %br
  %hr

=render 'comments/index', commentable: @note
=render 'comments/new', commentable: @note