config/routes.rb
SocialStudy::Application.routes.draw do

  resources :entries, except: [:show, :create] do
    collection do
      get 'next/:title', action: 'next'
      get 'history'
    end
  end

  match "/search" => "search#index", :as => :search

  resources :reviews, except: [:index]
  resources :notes, except: [:index]
  resources :experiences, except: [:index]
  resources :reminds, only: [:index] do
    collection do
      get :short_index
    end
  end

  resources :comments, only: [:create, :destroy] do
    collection do
      get :paginate
    end
  end


  resources :microblogs
  resources :states, only: [:show, :destroy] do
    member do
      post :relay
    end
  end


  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  resources :users, :only => [:show, :update] do
    member do
      post :follow
      post :unfollow
      get :following
      get :followers
      post :vote
      post :study
      post :grade
      post :collect
      get :states
      get :describe
      get :cancel_describe
      put :update_describe
      get :knowledges
      get :resources
      get :reviews
      get :notes
      get :experiences
    end
  end
  resources :knowledges, expect: :destroy do
    member do
      get :notes
      get :experiences
      get :my
    end
    collection do
      get :top
      get :top_experiences
      get :top_notes
    end
  end

  resources :resources, expect: :destroy do
    collection do
      get :top
      get :top_experiences
      get :top_reviews
    end
  end

  root :to => "states#index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  ROLES = %w(admin user)

  has_many :microblogs
  has_many :knowledges
  has_many :resources
  has_many :entries
  has_many :relays
  has_many :notes
  has_many :experiences
  has_many :reviews
  has_many :comments
  has_many :reputations
  has_many :reminds, class_name: 'Audit', inverse_of: :receiver
  has_and_belongs_to_many :following, :class_name => 'User', :inverse_of => :followers
  has_and_belongs_to_many :followers, :class_name => 'User', :inverse_of => :following

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :description

  validates_presence_of :name, :encrypted_password, :role
  validates_uniqueness_of :email, :case_sensitive => false
  validates_inclusion_of :role, in: ROLES
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  before_validation(on: :create) do
    self.role = 'user'
    self.name = self.email.split('@').first
  end

  def created_nodes_count_today
    self.knowledges.where(:created_at.gt => Date.today).count +
    self.resources.where(:created_at.gt => Date.today).count
  end

  def role?(target_role)
    self.role == target_role.to_sym || self.role == target_role.to_s
  end

  def image(version=:normal)
    case version
    when :small
      'default-user-small.png'
    else
      'default-user.png'
    end
  end

  def followed?(user)
    self.following_ids.include? user.id
  end

  def can_follow?(user)
    !(([self.id] + self.following_ids).include? user.id)
  end

  def follow(user)
    self.following << user
  end

  def unfollow(user)
    self.following.delete(user)
  end

  def repute(item, type)
    Reputation.create!({
      user: self,
      reputable: item,
      type: type
    })
  end

  def reputation_with(item)
    begin
      Reputation.where({user_id: self.id, reputable: item})
    rescue Mongoid::Errors::DocumentNotFound
      nil
    end
  end

  def relay?(relayable)
    return false if self.relays.blank?
    self.relays.map(&:relayable).include? relayable
  end

  def relay(relayable)
    if relayable.user != self
      relay = relayable.relays.new(user_id: self.id)
      relay.save!
    else
      return false
    end
  end

  def unrelay(relayable)
    relay = Relay.where(relayable: relayable, user_id: self.id).first
    relay.destroy
  end

  def all_reminds
    reminds = self.reminds.desc('created_at').to_a
    reminds.present? ? reminds.uniq{|e| e.modified["auditable_id"]} : []
  end

  def unread_reminds
    unread_reminds = self.reminds.desc('created_at').where(unread: true).to_a
    if unread_reminds.present?
      unread_reminds.uniq{|e| e.modified["auditable_id"]}
    else
      []
    end
  end

  def read_all_reminds
    self.unread_reminds.map do |remind|
      remind.update_attributes(unread: false)
    end.count
  end

  def study_state(knowledge)
    self.reputations.where(reputable: knowledge).
         in(type: Reputation::StudyTypes).first.try(:type)
  end

  def grade_state(resource)
    self.reputations.where(reputable: resource).
         in(type: Reputation::GradeTypes).first.try(:type)
  end

  def special_entry_by(type)
    return nil if type.blank?
    begin
      self.entries.find_by(type: type)
    rescue
      Entry.send("create_#{type}_with", self.id)
    end
  end

  ## Database authenticatable
  field :name,               :type => String
  field :operate_node_count, :type => Integer, default: 0
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  field :role,               :type => String
  field :description,        :type => String

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :notes, :knowledges, :resources, :notes, :reviews, :experiences, :states, :following, :followers]
  before_filter :get_reputable, only: [:vote, :study, :grade, :collect]

  def show
    @user = User.find(params[:id])
    @entry = @user.special_entry_by('default')
    @partial_path = 'entries/index'
  end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def following
    user = User.find(params[:id])
    @users = user.following.page(params[:page]||1).per(48)
    respond_to do |format|
      format.html{render 'index', locals: {title: "#{user.name}关注的人："}}
    end
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers.page(params[:page]||1).per(48)
    respond_to do |format|
      format.html{render 'index', locals: {title: "关注#{user.name}的人："}}
    end
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow @user
    respond_to do |format|
      format.js
    end
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow @user
    respond_to do |format|
      format.js
    end
  end

  def states
    @user = User.find(params[:id])
    @states = Audit.state.in(modifier: @user).desc('created_at').page(params[:page]||1).per(20)
    respond_to do |format|
      format.html
      format.js { render 'states/paginate' }
    end
  end

  # vote useful or useless
  def vote
     # cancel previous votes
    if (reputation = @reputable.reputations.
                                 where(user_id: current_user.id).
                                 in(type: Reputation::VoteTypes).first).present?
      @pre_vote_type = reputation.type
      reputation.destroy
    end

    # if previous vote type not equal current vote type, then vote
    if params[:vote_type] != @pre_vote_type
      @reputation = @reputable.reputations.create!({user: current_user, type: params[:vote_type]})
    end
    respond_to do |format|
      format.js
    end
  end

  def study
    # cancel previous study
    if (reputation = @reputable.reputations.
                                 where(user_id: current_user.id).
                                 in(type: Reputation::StudyTypes).first).present?
      @pre_study_type = reputation.type
      reputation.destroy
    end
    if params[:study_type] != @pre_study_type
      @reputable.reputations.create!({user: current_user, type: params[:study_type]})
      @study_state = params[:study_type]
    end
    respond_to do |format|
      format.js
    end
  end

  def grade
    # cancel previous grade
    if (reputation = @reputable.reputations.
                                 where(user_id: current_user.id).
                                 in(type: Reputation::GradeTypes).first).present?
      @pre_grade_type = reputation.type
      reputation.destroy
    end
    if params[:grade_type] != @pre_grade_type
      @reputable.reputations.create!({user: current_user, type: params[:grade_type]})
      @grade_state = params[:grade_type]
    end
    respond_to do |format|
      format.js
    end
  end

  def collect
    if (reputation = @reputable.reputations.
                              where(user_id: current_user.id).
                              in(type: 'collect').first).present?
      reputation.destroy
    else
      @reputable.reputations.create!({user: current_user, type: params[:collect_type]})
      @collect_state = params[:collect_type]
    end
    respond_to do |format|
      format.js
    end
  end

  def describe
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update_describe
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.js
      else
        format.js {'cancel_describe'}
      end
    end
  end

  def cancel_describe
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  ["notes", "experiences", "reviews"].each do |field|
    define_method field do
      @user = User.find(params[:id])
      @items = @user.send(field)
      @partial_path = 'common/leaves'
      render template: 'users/show'
    end
  end

  def knowledges
    @user = User.find(params[:id])
    types = params[:type].present? ? params[:type] :  Reputation::StudyTypes
    @reputations = Kaminari.paginate_array(
                              @user.reputations.knowledges.in(type: types)
                            ).page(params[:page]).per(10)
    @reputation_types = Reputation::StudyTypes
    @partial_path = 'nodes'
    render template: 'users/show'
  end

  def resources
    @user = User.find(params[:id])
    types = params[:type].present? ? Reputation::GradeTypes : ['collect']
    @reputations = Kaminari.paginate_array(
                              @user.reputations.resources.in(type: types)
                            ).page(params[:page]).per(10)
    @reputation_types = ['评分']
    @partial_path = 'nodes'
    render template: 'users/show'
  end



  protected
  def get_reputable
    @reputable = params[:reputable_type].constantize.find(params[:reputable_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def whos(string)
    if current_user.present? and current_user == @user
      '我' + string
    else
      @user.name + string
    end
  end
end

app/views/users/_describe_form.haml
= form_for @user, url: update_describe_user_path(@user), remote: true do |f|
  .field
    = f.text_area :description, class: 'span12'
    = f.submit '提交', class: 'btn btn-success'
    = link_to '取消', cancel_describe_user_path(@user), class: 'btn', remote: true

app/views/users/_menu.haml
%div
  %ul.nav.nav-pills
    %li
      = breadcrumb_li user_path(@user) do
        维基
      = breadcrumb_li knowledges_user_path(@user) do
        知识
      = breadcrumb_li resources_user_path(@user) do
        资源
      = breadcrumb_li notes_user_path(@user) do
        笔记
      = breadcrumb_li reviews_user_path(@user) do
        评论
      = breadcrumb_li experiences_user_path(@user) do
        心得
%hr.clear

app/views/users/_nodes.haml
- if @reputation_types.present?
  %ul.nav.nav-tabs
    = full_breadcrumb_li request.path do
      收藏
    - @reputation_types.each do |type|
      = full_breadcrumb_li "#{request.path}?type=#{type}" do
        = type

- if @reputations.present?
  - @reputations.each do |r|
    - node = r.reputable
    .profile
      .profile-left
        = link_to node do
          = image_tag node.image, class: 'normal pull-left'
      .short-info
        = link_to node do
          %h3 #{node.title}
        %br
        %p
          = raw node.description
    .pull-right
      = repute_icon(r.type)
    %hr.clear
  .pull-right
    = paginate @reputations

app/views/users/_rmod_info.haml
.span6
  =link_to user, class:'user-face' do
    =image_tag user.image
%h4.span6.text
  = link_to user.name, user
%br.clear
%br
.right-line.pull-left
  关注
  %br
  =link_to user.following.count, following_user_path(user), target: '_blank'
  人
.right-line.pull-left
  粉丝
  %br
  =link_to user.followers.count, followers_user_path(user), target: '_blank'
  人
.pl10.pull-left
  广播
  %br
  =link_to user.microblogs.count, states_user_path(user), target: '_blank'
  条

app/views/users/cancel_describe.js.erb
$('#user-describe').html('<%= j render 'description'%>');

app/views/users/collect.js.erb
span = $('.collect-link span')
<% if @collect_state.present? %>
    span.text('已收藏')
<% else %>
    span.text('收藏')
<% end %>

app/views/users/describe.js.erb
$('#user-describe').html('<%= j render 'describe_form'%>');

app/views/users/follow.js.erb
$('.follow-btn').html('<%= unfollow_btn %>')

app/views/users/grade.js.erb
gradeObj = $('<%= ".grade-#{@grade_state}" %>')
App.Reputation.hardStar(gradeObj)

app/views/users/index.haml
.span7.well
  %h4
    =title
  %br
  - @users.each do |user|
    %div.pull-left.span2
      = link_to user do
        = image_tag user.image(:small)
        %br.lh3
        .text
          =user.name
      %br

  .pull-right
    = paginate @users, remote: true

app/views/users/microblogs.haml
.span8.well
  %h4
    ="#{@user.name}的广播:"
  %hr
  =render 'microblogs/index'

app/views/users/states.haml
.span8.well
  %h4
    ="#{@user.name}的广播:"
  %hr
  =render 'states/index'

app/views/users/study.js.erb
$('.operations .study-type .alert-success').removeClass('alert-success').addClass('alert-info')
$('<%= ".operations .study-#{@study_state} .alert" %>').addClass('alert-success').removeClass('alert-info')

app/views/users/update_describe.js.erb
$('#user-describe').html('<%= j render 'description'%>');