config/routes.rb
SocialStudy::Application.routes.draw do

  resources :entries, except: [:show, :create] do
    collection do
      get 'next/:title', action: 'next'
      get 'history'
    end
  end

  match "/search" => "search#index", :as => :search

  resources :reviews, except: [:index]
  resources :notes, except: [:index]
  resources :experiences, except: [:index]
  resources :reminds, only: [:index] do
    collection do
      get :short_index
    end
  end

  resources :comments, only: [:create, :destroy] do
    collection do
      get :paginate
    end
  end


  resources :microblogs
  resources :states, only: [:show, :destroy] do
    member do
      post :relay
    end
  end


  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  resources :users, :only => [:show, :update] do
    member do
      post :follow
      post :unfollow
      get :following
      get :followers
      post :vote
      post :study
      post :grade
      post :collect
      get :states
      get :describe
      get :cancel_describe
      put :update_describe
      get :knowledges
      get :resources
      get :reviews
      get :notes
      get :experiences
    end
  end
  resources :knowledges, expect: :destroy do
    member do
      get :notes
      get :experiences
      get :my
    end
    collection do
      get :top
      get :top_experiences
      get :top_notes
    end
  end

  resources :resources, expect: :destroy do
    collection do
      get :top
      get :top_experiences
      get :top_reviews
    end
  end

  root :to => "states#index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

app/models/experience.rb
class Experience
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Post

  has_many :reputations, as: :reputable
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  belongs_to :experienceable, polymorphic: true, inverse_of: :experienceable

  attr_accessible :user_id, :user, :experienceable, :title, :content

  validates_presence_of :user_id, :experienceable, :title, :content

  scope :knowledge, where(experienceable_type: 'Knowledge')
  scope :resource, where(experienceable_type: 'Resource')

  index :user_id => 1

  field :title, type: String
  field :content, type: String
  field :reputations_count, type: Integer, default: 0

  alias_method :itemable, :experienceable
  scope :top, ->(num=nil){ desc(:reputations_count).limit(num) }

  def repute_count(type)
    self.reputations.where(type: type).count
  end

  def short_content
    self.content.first(1000)
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  load_and_authorize_resource
  before_filter :require_user, except: [:show, :index]
  before_filter :get_experienceable, only: [:new]
  layout :choose_post_layout

  def get_experienceable
    @experienceable = params[:experienceable_type].constantize.find(params[:experienceable_id])
  end

  def index
    @experiences = Experience.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @experience = Experience.find(params[:id])
    @experienceable = @experience.experienceable
  end

  def new
    @experience = @experienceable.experiences.new(user_id: current_user.id)
  end

  def edit
    @experience = Experience.find(params[:id])
    @experienceable = @experience.experienceable
  end

  def create
    @experienceable = params[:experience][:experienceable_type].constantize.find(params[:experience][:experienceable_id])
    @experience = @experienceable.experiences.build(params[:experience])
    @experience.user = current_user

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'experience was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @experience = Experience.find(params[:id])
    @experienceable = @experience.experienceable

    respond_to do |format|
      if @experience.update_attributes(params[:experience])
        format.html { redirect_to @experience, notice: 'experience was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url }
    end
  end

end

app/views/experiences/_form.html.haml
= form_for @experience do |f|
  .field
    = f.label '标题'
    = f.text_field :title

  .field
    = f.label :内容
    = f.text_area :content, class: 'textarea'

    = f.hidden_field :experienceable_type, value: @experienceable.class.name
    = f.hidden_field :experienceable_id, value: @experienceable.id

  .form-actions
    = f.submit '提交', class: 'btn btn-success'
    &nbsp;
    = link_to '返回', (@experience.new_record? ? @experienceable : @experience), class: 'btn'

app/views/experiences/_top.haml
- if @experiences.present?
  %h3
    %small 热门心得
  %br
  - @experiences.each do |experience|
    %div.span5{style: 'padding-bottom: 15px;'}
      %div
        =link_to experience.user do
          = image_tag experience.user.image(:small), class: 'user-face'
      %div.pull-left
        =link_to experience do
          %strong #{experience.title}
        %br.big
        =link_to experience.user.name, experience.user
        的
        =link_to experience.experienceable.title, experience.experienceable
        心得
        %br.big
        %small
          ="#{experience.reputations.useful.count}有用 #{experience.created_at.getlocal.to_date}"

app/views/experiences/_top_maxi.haml
- if @experiences
  %h3
    %small 热门心得
  %br
  - @experiences.each do |experience|
    %div{style: 'padding-bottom: 15px;'}
      %div
        =link_to experience.user do
          = image_tag experience.user.image(:small), class: 'user-face'
      %div.pull-left.span10
        %h4
          =link_to experience.title, experience
          =link_to '#', class: 'toggle-content' do
            %span.pull-right.icon-caret-down
        %p
        =link_to experience.user.name, experience.user
        的
        =link_to experience.experienceable.title, experience.experienceable
        心得
        %br.big
        %div.text
          .short-content
            = raw short_content(experience)
          .whole-content.hidden
            = raw experience.content
        %p
        %small
          ="#{experience.reputations.useful.count}有用 #{experience.created_at.getlocal.to_date} "
          =link_to experience_path(experience, anchor: "comments") do
            ="（#{experience.comments.count}评论）"
    %br.clear
    %hr

app/views/experiences/edit.html.haml
%h3
  = "修改 #{@experienceable.title} 的心得"
%hr

= render 'form'

app/views/experiences/index.html.haml
%h1 Listing experiences

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @experiences.each do |experience|
    %tr
      %td= experience.title
      %td= experience.content
      %td= link_to 'Show', experience
      %td= link_to 'Edit', edit_experience_path(experience)
      %td= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New experience', new_experience_path

app/views/experiences/new.html.haml
%h3
  = "写 #{@experienceable.title} 的心得"
%hr

= render 'form'

app/views/experiences/show.html.haml
%div.post
  %h4.pull-left
    = "#{@experience.experienceable.title} 的心得 - #{@experience.title}"

  %div.pull-right
    %div.reputations
      -if operable(@experience)
        = link_to edit_experience_path(@experience) do
          %i.icon-edit
        %span.w5
        = link_to @experience, method: :delete, confirm: '你确定要删除这条心得吗？'  do
          %i.icon-trash

  %br
  = link_to @experience.user.name, @experience.user
  在学
  = link_to @experienceable.title, @experienceable

  %br
  %small
    = @experience.updated_at.local

  %hr.clear

%div.text
  = raw @experience.content
%br.big

- if current_user
  .pull-right
    = collect_link(@experience)
    &nbsp;

    =link_to vote_path(@experience, 'useful'), remote: true, method: :post do
      %i.icon-thumbs-up
    %span.useful-count
      =@experience.repute_count('useful')

    &nbsp;
    =link_to vote_path(@experience, 'useless'), remote: true, method: :post do
      %i.icon-thumbs-down
    %span.useless-count
      =@experience.repute_count('useless')
  %br
  %hr

=render 'comments/index', commentable: @experience
=render 'comments/new', commentable: @experience