config/routes.rb
SocialStudy::Application.routes.draw do

  resources :entries, except: [:show, :create] do
    collection do
      get 'next/:title', action: 'next'
      get 'history'
    end
  end

  match "/search" => "search#index", :as => :search

  resources :reviews, except: [:index]
  resources :notes, except: [:index]
  resources :experiences, except: [:index]
  resources :reminds, only: [:index] do
    collection do
      get :short_index
    end
  end

  resources :comments, only: [:create, :destroy] do
    collection do
      get :paginate
    end
  end


  resources :microblogs
  resources :states, only: [:show, :destroy] do
    member do
      post :relay
    end
  end


  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => "users/omniauth_callbacks"
    } do
    get "account/update_private_token" => "account#update_private_token", :as => :update_private_token_account
  end

  resources :users, :only => [:show, :update] do
    member do
      post :follow
      post :unfollow
      get :following
      get :followers
      post :vote
      post :study
      post :grade
      post :collect
      get :states
      get :describe
      get :cancel_describe
      put :update_describe
      get :knowledges
      get :resources
      get :reviews
      get :notes
      get :experiences
    end
  end
  resources :knowledges, expect: :destroy do
    member do
      get :notes
      get :experiences
      get :my
    end
    collection do
      get :top
      get :top_experiences
      get :top_notes
    end
  end

  resources :resources, expect: :destroy do
    collection do
      get :top
      get :top_experiences
      get :top_reviews
    end
  end

  root :to => "states#index"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
end

app/views/resources/_form.html.haml
%br
= form_for @resource do |f|
  .field
    = f.label :title, '标题 *'
    = f.text_field :title
  .field
    = f.label :url, '参考网址'
    = f.text_field :url
  .field
    = f.label :description, '描述 *'
    = f.text_area :description, class: 'textarea'
  .actions
    = f.submit '提交', class: 'btn btn-primary'
    = link_to '返回', :back, class: 'btn'

app/views/resources/_sidebar.haml
%div#sidebar
  %ul.nav.nav-pills.nav-stacked
    = breadcrumb_li resources_path do
      %strong 广场

    = breadcrumb_li top_resources_path do
      更多学习资源

    = breadcrumb_li new_resource_path do
      创建学习资源

    %div.h358

    = breadcrumb_li top_experiences_resources_path do
      更多使用心得

    = breadcrumb_li top_reviews_resources_path do
      更多评论

app/views/resources/edit.html.haml
%h3 修改学习资源

= render 'form'

app/views/resources/index.html.haml
%div
  =render 'common/carousel', title: '最新资源', items: @newest_resources
  %hr
  =render 'common/carousel', title: '热门资源', items: @hottest_resources
  %hr
%div
  =render 'experiences/top'
  %hr.clear
  =render 'reviews/top'

app/views/resources/new.html.haml
%h3 新建学习资源

= render 'form'

app/views/resources/show.html.haml
%div.profile
  .profile-left
    = image_tag @resource.image, class: 'normal pull-left'
    - if @resource.url.present?
      = link_to '参考地址', @resource.url, class: 'update-link', target: '_blank'
      %br.big
    = link_to '更新该资源', edit_resource_path(@resource), class: 'update-link'

  %div.info
    %h3
      = @resource.title
    %div
      = raw @resource.description

%br.clear
-if current_user
  %div.operations
    %hr
    = collect_link(@resource)
    &nbsp;
    我的评价:
    - Reputation::GradeTypes.each do |type|
      = link_to '', grade_path(@resource, type), method: :post, remote: true,
        class: "grade-#{type} grade-type #{type.to_i <= current_user.grade_state(@resource).to_i ? 'hard-graded-type icon-star' : 'icon-star-empty'}"
    %br
    %br

    =link_to new_review_path(resource_id: @resource) do
      %li.icon-pencil
      写评论
    &nbsp;
    =link_to new_experience_path(experienceable_id: @resource, experienceable_type: @resource.class.name) do
      %li.icon-file
      写使用心得
%hr

=render 'experiences/top_maxi'
=render 'reviews/top'